<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Manage</strong> Games' => 'Spiele <strong>verwalten</strong>',
    'Date' => 'Datum',
    'Game' => 'Spiel',
    'GameCenter' => 'GameCenter',
    'Games' => 'Spiele',
    'Percent completed' => 'Prozent erreicht',
    'Player' => 'Spieler',
    'Show more' => 'Mehr anzeigen',
    'Updated at' => 'Aktualisiert am',
    'Updated by' => 'Aktualisiert von',
    '<strong>Game</strong> tags' => '',
    'Achievement' => '',
    'Achievements' => '',
    'Achievements HELP' => '',
    'All' => '',
    'Any' => '',
    'Archived' => '',
    'By Name' => '',
    'Created at' => '',
    'Created by' => '',
    'Description' => '',
    'Find Games by their description or by their tags' => '',
    'Following' => '',
    'Is Completed' => '',
    'Last Reported Date' => '',
    'Manage Games' => '',
    'Member' => '',
    'Module' => '',
    'Name' => '',
    'Neither..nor' => '',
    'Newest first' => '',
    'No results found!' => '',
    'Oldest first' => '',
    'Score' => '',
    'Search...' => '',
    'Sorting' => '',
    'Status' => '',
    'Tags' => '',
    'Title' => '',
    'Try other keywords or remove filters.' => '',
    '<strong>Games</strong>' => '@@<strong>Spiele</strong>@@',
    'Achievement Description' => '@@@@',
];
