<?php

/**
 * @package GameCenter
 * @author  Christian Seiler <christian@christianseiler.ch>
 * @since   1.0.0
 */

namespace fhnw\modules\gamecenter\models;

use humhub\components\ActiveRecord;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "Report".
 *
 * @property int $id
 * @property int $game_id
 * @property int $player_id
 * @property string $option
 * @property string $value
 * @property-read string $timestamp
 * @property-read \fhnw\modules\gamecenter\models\Game $game
 * @property-read \fhnw\modules\gamecenter\models\Player $player
 */
class Report
  extends ActiveRecord
{

  public const TABLE = 'game_report';

  /** @returns string */
  public static function tableName(): string { return self::TABLE; }

  /**
   * @param bool $insert
   *
   * @return bool
   */
  public function beforeSave($insert): bool
  {
    if ($insert) {
      $this->timestamp = date('Y-m-d G:i:s');
    }

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getGame(): ActiveQuery { return $this->hasOne(Game::class, ['id' => 'game_id']); }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getPlayer(): ActiveQuery { return $this->hasOne(Player::class, ['id' => 'player_id']); }

}
